# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/IMT-GIS-Tools',
                'doc_host': 'https://imt-things.github.io',
                'git_url': 'https://github.com/imt-things/IMT-GIS-Tools',
                'lib_path': 'IMT_GIS_Tools'},
  'syms': {}}
